name: Fullstack PM2 Docker Deploy

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. 安装 pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 4. 登录 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 5. 构建 Docker 镜像
      - name: Build Docker image
        run: |
          REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d'/' -f2 | sed 's/\.git$//')
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${REPO_NAME}:latest .

      # 6. 推送 Docker 镜像
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:latest

      # 7. 部署到服务器
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /var/www/app
            cd /var/www/app || exit 1

            CONTAINER_NAME="${{ github.repository_owner }}"
            IMAGE_NAME="${{ secrets.DOCKER_HUB_USERNAME }}/$(echo "${{ github.repository }}" | cut -d'/' -f2 | sed 's/\.git$//'):latest"

            echo "容器名称: ${CONTAINER_NAME}"
            echo "镜像名称: ${IMAGE_NAME}"

            docker pull ${IMAGE_NAME}
            docker stop "${CONTAINER_NAME}" || echo "容器不存在，无需停止"
            docker rm "${CONTAINER_NAME}" || echo "容器不存在，无需移除"
            docker image prune -f
            
            docker run -d \
              --name "${CONTAINER_NAME}" \
              --restart=always \
              -p 8083:80 \
              -v /resource:/resource \
              -v /var/log/pm2:/var/log/pm2 \
              ${IMAGE_NAME}